import { createTypes } from 'reduxsauce';

export default createTypes(`
	NAME_REQUEST
	NAME_RECEIVED

	FIND_GYMS_REQUEST
	GYM_RESULTS_SUCCESS
	GYM_RESULTS_FAILURE

	STORE_PLACE
	STORE_LOCATION_MARKER
	STORE_CURRENT_LOCATION

	GET_DISTANCE
`);
